ErrorRevaler: GTK4 preparations
elementary/switchboard-plug-useraccounts pull request #198
Opened 2023-09-23 12:56 UTC by leolost2605

- Don't derive from `Gtk.Revealer` 
- construct with properties
- Some cleanup like not storing the label property as it's not used anywhere
- Don't set the label property in the Object call as that required a null check on the label widget. Can be reverted if wanted

2023-09-24 11:55 UTC, jeremypw requested changes
Looks good - no regressions found. Only comment is why not derive from Gtk.Bin as there is only ever one child? Then orientation setting is not needed.

2023-09-24 13:05 UTC, leolost2605 commented
`Gtk.Bin` isn't available in GTK4 so I think if we want to derive from something we'll eventually have to use Gtk.Box or Grid anyway

2023-09-24 17:08 UTC, jeremypw commented
Well, you can use Gtk.Widget with a Gtk.BinLayout in Gtk4.

2023-09-24 17:27 UTC, leolost2605 commented
Sure if that is simpler/should be preferred... 🤷

2023-09-25 09:16 UTC, jeremypw commented
Its no big deal - just removes the need for an orientation but it can be considered later when porting. I'll approve as is.

2023-09-25 09:16 UTC, jeremypw approved these changes

2023-09-25 09:17 UTC, merged