CropView: subclass DrawingArea
elementary/switchboard-plug-useraccounts pull request #213
Opened 2023-12-30 19:13 UTC by danirabbit

No EventBox in GTK 4, so subclass DrawingArea and use EventControllers. Review with "hide whitespace"

2024-01-01 16:36 UTC, jeremypw requested changes
Minor code issue.  Otherwise works the same as master with same terminal warnings.  The selection square does not behave as expected, especially when dragging top left corner, but master is the same so can be left for another PR.

2024-01-01 16:36 UTC, jeremypw commented on src/Widgets/CropView.vala
> +        critical ("we got motion");
This should be removed or made `debug`

2024-01-01 20:18 UTC, danirabbit commented on src/Widgets/CropView.vala
> +        critical ("we got motion");
Woops, thanks for noticing that

2024-01-03 12:50 UTC, jeremypw approved these changes

2024-01-03 12:50 UTC, merged